;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        Buffer-menu-delete
        Buffer-menu-execute
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        ourcomments-ido-switch-buffer-or-next-entry
        undefined
        ))
